# Travis config file
# ==================

language: python

python:
  - "3.6"

branches:
  only:
    - master

services: mongodb

# Install test dependencies
before_install:
  - pip install pytest pytest-cov
  - pip install codecov

# Install project depencies
install:
  - pip install -r requirements.txt --quiet

# Run automated tests
script:
  - py.test --cov flask_auth --cov-report term-missing --cov-config flask_auth/tests/.coveragerc flask_auth/tests

# Submit coverage report to coveralls
after_success:
  - codecov
